nexus:
  image:
    tag: 3.64.0
  securityContext:
    runAsUser: 200
    runAsGroup: 200
    fsGroup: 200
  persistence:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 10Gi
  nexus:
    docker:
      enabled: false
    env:
      - name: INSTALL4J_ADD_VM_PARAMS
        value: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
  ingress:
    enabled: false
