---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velocity-forwarding-secret
spec:
  encryptedData:
    forwarding.secret: AgA8/KUBBm9lIFZnksrj1HlpkvUAoLCAReaOMivqz6sehu/ayu89fe2QgEgXC9niregsRAONzseI1ePpM6+OYzqL6+22dZ3d8MEL7e033sbVNE/L2D+dFh3ufTnyR2rdrWex1JQK0CRZydUkfhkP/njCTLXdPeHa+E8+P2HMhjiTTLLXHHgIn7zUKQXqV5sFH/4vEKFVFA0idJxmRv3foqRdTpw4kH69Z5obPm9db/d0RdpBuYSJHfhPSL+wKzXjx3i6S/VX/li8sDoCYpAIn7DBqt6cF7LhYjdsFLVIHzBb9vBl21sKCu3fi0PCeLnTZW5ziCz9+gcoq5sJI1G9pUnrbkCXsNrWIhsJ/pkvFo8SJbUaoDcAPR8dnSEl6urt4ZUG0YOXq/7QxmPH36cK+YuL7eEg5QoIRByPvOk/tdQuD01B0Gai2vXuGN7P/wdRAy+lir059EWBHoDkbYM0YmYwSbBf2o4hTjBgUrZcZ4vbnfBaoBYMSM2yKe+wATUQIb5QdoH6iaUoatGuEL8o8jmJcgmJlcXh8fHWLAacmyzT5Qgocb8K6URZGp/2pLvZ+uUMTFR6gSHBHOgUUMiouug81msvyMMArFdwfXZ5Ixi1OIKu5crO9Z3VVASXDri8sCNHXWNcHUrA2KjJUij+glqHs/UDXUf+dsD/0VDHGhaG+C0zBR2dW3nrzqOQUsp9B5Kqpl2lNGJ6HL4ftgQC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: velocity-forwarding-secret
