apiVersion: v1
kind: PersistentVolume
metadata:
  name: world-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/world
    type: DirectoryOrCreate
