namespace: registry
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
#  - secret.yaml
  - servers-transport.yaml
  - ingress-route.yaml

secretGenerator:
  - name: registry-auth
    files:
      - htpasswd
    type: Opaque
