apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: public-realm-fleet
  namespace: realm
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: realm-paper
        image: registry:5000/realm-paper:latest
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
