apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespaces
resources:
  - realm-namespace.yaml
  - registry-namespace.yaml
  - jenkins-namespace.yaml
  - database-namespace.yaml
  - gameserver-fleet.yaml
  - velocity.yaml
  - jenkins.yaml
  - docker-registry.yaml

generators:
  - agones-chart.yaml
  - scylla-chart.yaml
