apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.kubernetesCRD"
    ports:
      traefik:
        port: 9000
        expose:
          default: true
      web:
        port: 80
        expose:
          default: true
      websecure:
        port: 443
        expose:
          default: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
