apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  namespace: realm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: velocitypowered/velocity:3.1.2
        ports:
        - containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: velocity
  namespace: realm
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: velocity
