---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    CF_API_EMAIL: AgCYY3oT4bxHThEwXypn7rKnaBxp4f2jRhnblFePp73ifeSIr34h6W38yHJDxggtMrb1DzW0HKVYpM5ULNYMjAIwgquAe18Kt3YTJiEJb0idLRBpqfdsqmnEwE4VLQNht+Smn7JqXYHkgsFvBwvh4bvLa/Q+E/FL7kuU8Ew8MriMjzP++n+S5ATpjaBe8fMl9ez3heacrwwIwQ+LJfoCvmwq2lghNHeZO4KKuux0CxZH5YyPqp3SPWzKJRaUsyUTwvrmfMBtHYV8YVkfOgZtPmlaJQkvy6q/gIVYmjiwvfEdyi6Tw2f4lgYgjvZzpXhcpRQxc8fRmyoDb1eTmVay61hMt3J75KyqcpFofOaHsDGZ12VE9ttRCvALZo937Cvoqg0e9GZz2HVvTi5J12XpEJZaGQxsU4X4+/ZBgRmDRF+5uVHXZqsGxuM0qINQEOauZI993ozVKTGfWGTmz7EAQ2IOBp7qkbFCAKky14cibayNiDRoztOB0iKcUGXYSIhRIDkrm9ZVfTUMk7+wNc9XAmJ01Fl6JNiQVTE1zGdlv65/eIqeHJH60xJMztUlO7JQZyHfioR2DFFwAFodtVixYanQWl3QVO1uX00UQB5XDVuWxFOiSAdc7JMmPmk/Od0WK5gzL5RJGXhSbm2jPjkniS2hIG6fJe4LrfDFZ7TWt3Go1Jafgkp3wgCNdNSp+rYMDU6pahjKVLVmThfZnk+WQK8/zpS0lw==
    CF_DNS_API_TOKEN: AgAKNNviG3Ka1/Zl9TvsWWBhWAoD0YGSEbHRHhJpxm/7MlE1382IKN3csjEXVE2pjVeH6k/zqXZbnM+PqOMJpgApORJYBVautW8pEBHZb0R51utKFyWLdDOkbb9k8AcsNvjjuBx3FzKR4jD4GxQ1jpn2kclQ+Go1+jOffq4310NTa/uwxjaWLjdercrGlVj4cuqg6k8Pg0XlGlfrKcAy0SuPe529bvEsEINLuTP4/ITQUHFlPGvgXkl19iISSGrasM1AHiHAG64PmoJ9rhmq8EAf+YSN6dOa33wJb5RYtkdvRjmdfHQ8X4jimCBhJ+2SYjuwkt04cvnD5VlVj+5TaPMDUpKtKn5luK6GhN+mIkx5+dNz3WHtvFnOeqp4aT6YRZrqrjUUYp88gAT0oVrbi+Z/JDXcLISSshQIe6NmFVxDJsZa2OLFFYtrd62zyXFQoXM6oUEOX2AcZUQKbRdvKiA6MpixU87ytB0ayVdEEWU/4bIfTeh20NVA2Fs0qYEWAofDiRTzoofa4y4Tt98hNbhjahIb0cBnRAb4ixFBQRkbomvP38TZ0kDcYNs22lqpLc04ZxOqwbEKYpUllP/nS/jhMhQHVD574tAyL95QNfjux7C1Rf5Zd1UdqzLIQzgfPXzS4dLsz7UXIVypjNXEDg7Y1n6ZOtvN/LuowAvz4uzHIePUcyphig+nARqbt8Ll1jICYq2mkJ2ytr5czdxhpjd32sWzDVO/JlLK6lyWkM0p9y1t2h74RFvN
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: traefik
