apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/traefik/traefik/v3.3.5/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - cloudflare-sealed.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 34.5.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
