additionalArguments:
  - --entrypoints.web.http.redirections.entrypoint.to=websecure
  - --entrypoints.web.http.redirections.entrypoint.scheme=https
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=runicrealms.com
  - --entrypoints.websecure.http.tls.domains[0].sans=*.runicrealms.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=runicrealms.mc@gmail.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
  - --api=true
  - --api.dashboard=true
  - --api.insecure=true
  - --providers.kubernetesCRD

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token-secret
        key: CF_DNS_API_TOKEN

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: true
  size: 128Mi
  path: /certs

ports:
  realm:
    port: 25565
    expose:
      default: true
  realm-dev:
    port: 25566
    expose:
      default: true
  traefik:
    port: 9000
    expose:
      default: true
  web:
    name: web
    port: 80
    expose:
      default: true
  websecure:
    tls:
      enabled: true
    name: websecure
    port: 443
    expose:
      default: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
