---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: velocity-forwarding-secret
  namespace: realm-dev
spec:
  encryptedData:
    forwarding.secret: AgBs0OXk2DZw5bmWgxGjfns+kxRmRDvqmWFPEexZtdQBJIuGAGqQetIN25dziKyxNX9VVDIGU/ti2ta/ui0BN/AObXeHupmcYNne5qN/YBPzzE3IYq9dNC8fVCLDGhYzGVNbiwoQ0a2SiufhyX69EEwnuH8fPVsLo+Qeu7y2dNeakrUWLsqs9+KXS5OvqoDeUrPV6ntHaaKlLw/KLbbVM6StYN1+/XIRc04lQCjXdtvkHKugVUXpmD3JYG8TEPRL2tVzRG0n7f9K/MkpnfDau4Xfh6oe7fBGPtfuCBnDKUAZdjd/R6JztvytE9BBc8OYwkferZjKTrRXbnu/7VF92Gs2oViKRevmhyKIksW97ZItu70Xn9fYqnMIbMTTKvaGE/LEue71MrVhqzvoPR+qFxxELeGvww7Ai4HBrDr87pILxXU2LO2gB2OiulycWrSFCpAZU5+q1yqJWAxq6g2VQkhndIxHnw2SNF191ZZ1YWngzVEn9oKSc6Bxs1qG6FKm8dVG0Tsq0jMoDDLxb5AhScouPnRwPiM3HaxRHwcIxumzypJIsSuPzpdZFnX4NjQMCXi5hMJFmhU6amFU/oesvOuFl5sagt4lTUhTxsAwbZDQGDIY6DAyJa4GctOMqi+nsoidjKLnLYjn15sGrUUNdbndT0BpiPVcuPQSVMR8RX47wnExBTdTonLsdUKxwYKAKdokIy9z21MdY0i/gtxgx80hS7wZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: velocity-forwarding-secret
      namespace: realm-dev
