---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: velocity-forwarding-secret
  namespace: realm
spec:
  encryptedData:
    forwarding.secret: AgAq0PsebQsHF1+dZGuFyE+TL9WpMj1R6LqFieDUOmKvA+82J8U+ovC0uVg8rZKQd+4IGarHnPlGS9FNV7ZjZV9ju4wCOrzxYLjsQAx0pRPj9NmbliC7KKojE86wPQYVTdTvrT8MapbqkuYWyFrNvGv+qrh9PEKkmjK0OiMGdb+S/qjPif8msMfV0uYCprDVumnj0jbeuQGtNif/H1YO0pyKGuP52oln4hrFk0nQZ/ikUY1NrD86xenWCqIlTl3wsGuuqXRWjqJcOhCDbFuRGVa9ADuKhVlJw2is3FKPKbYH+70ujG/FCAhVRA6lj3k9aeP6ILYI6uy1Fkr4at/Gm9hZs5zYQgbS07QEiuuAwcBZM7Yd7Q1UXsKRqZTU0yl9b1bZTVd8QybMUE4qMMxoUnHpfLqdxVQt8TjdhflEkxpzRJDBPoELr1LNRQ3CTQ6ofxzxVD55A+pkBpB2Z9dtnt6yX+tYEW+ANT/lMNrT7R/R1jn2gojI8bmekMe9bgRN7oGdrQrTLoTtMohA5xw7lim5skTqKXSTpnsaXt6ged5Z6AmqtbYzEgOZnsXnuP+jckFMfv6cjmVjl2ng/yOPdoYF/NaG1bezZviecqMSo6piJdziT9sy/C7t4sH5WulWoB7Gzgb10ke0sfy6Q48Z6zl3qyLqF3pYtw/FdW1WTcUq2db5d9hVIrxLIUffJex39FRzvyoUlPLwHdGiysN3vTSd08Iq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: velocity-forwarding-secret
      namespace: realm
