---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mongodb-secret
  namespace: realm-dev
spec:
  encryptedData:
    mongodb.secret: AgCly4Axmhdyn+EPjATNeXVygk7hr/GNLpioK85HBpLGtF6ZLzg6yql8a8fFmfXbgCpN2LF4QyUPtSZTQ9N6pQj/46LAvXZDH60/bTc1Db/vsI8cfTPdyUs0vJzRXHUbx2YNVpXtNeqonCDZ4o1CSjDelPLUWTea+Zzl9gIJ2ONyKdQkv1zCnd9z8t1bwzrzvS+MRSyEJv0UmNB1DnFYsROxrRPynGECEa2uU59P7PpR51CzoImadhNThrXOMuFEKbGkk1Vy6ckI7VHRogmuGhZi6Xr8uI+cGf34kxI9ELKITDme6PLXfFf9dDk3B55XMjGqRsI9Vde4Y3KEpJmf8TgJ/3jz7eKCbDF4FYau5bkdwTLNI+koFMhG83yEGkoWEoqZ6J/cU+HvR+RNVc8zLAo99FXoYRyOvIxGjrykBo9OuzR619KisJz7U/AWtX3PdCAv8u9ymMcFfHtf+bsy5ByP+0SK259pu8Mlo7XW8ufPdqhu02ipOSb5Ge7zuoD6/+vXkvtSQxiDAEQj9fM3FebQkzGikPJLEt5cmlCPImq3hMFZgttfErn5OL3MrBGBg+8CocVeiBPXC0jNt/gfB0bLQDg5efAcaXUC3uWuzXpEQ1PnqEJ36z15kwNKV5GNqAXZjGcy9j9iepWK169q6eHRYFMpA1BVYg40MI2AXV3Crbmbj0Ll8pARda3s3TGvhQLdUVrrraPS4az+nnBs+zfNPAhKLSG4XROBEU+O/+X2oqvcUS6HWhEuKcETQfTnxzIpdZRNO+FpgEd/DPQ6AI7G54/tKj/J0KgV54C1SOD8UpDsIrnrs5+ex0IenGWTRg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mongodb-secret
      namespace: realm-dev
