---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mongodb-secret
  namespace: realm
spec:
  encryptedData:
    mongodb.secret: AgAI197+6zYBLCm0UbhSwyy6kAXn9rYGAiTF0UTwOu2Czeqb7rhd4Gorznig0SXGs047D+lmSlErutNwLx3053OKXLr5NG4rg7rXJ3VQqzneFDeo199HwB9dQDsGbDbTSuf6WO/qqi5fKXb2ONZr/+KtDRUuIaKhrtAHu/rciBfMsur/90jLW3RTN0t+ifpsQK3WQCywJgF94pe+d+b758lIqqGhiYjOHb7uxQYAdWHAHeqfSrQPHNO447ev2q0Dju6Z03eb33K4ngibEl+ZWvDyKmftHTzGbBAGSYmcszuADhema76fubhdz+F4KvKPf5Ctn+Y3nUIMEP2UJH5ByXX3G/srOfGVLi0/fBFCwcl+8Xb+lGV6hC9482fCy8LByA0TOELBfOwBQG4LbTYNI7+j7yMBSwyNdFiLJ5GOSBNm7HU1v/mH1twfljIJWaBI67gaP6jJTuezS5w+K8PMivkSA7HS5enQBgXpNNUmqefro/jae2W7R2Gjv/FjZtGD4ZBBOtu1xjaeGNvQ5mavFJLisqYj4s0EXXRgjP0JGsPJql7JS8XZUXi0sEvi5+lHhg7PZTBRTwVhbfXe3h+PJeWodzyCkitxEQGJ6oc7Ka7MeDeBEq8OEQnCupAF8Fc+RPFdl7uSVg589qIWoyL6N0h6bxJgASs8aZIiuj5Q8Z4rNxVe97TrFISidIj5HvjaHrP5RWm5yuo/AY4qSpmp5iSPwVV8SLEOjElVnpHM/PdfNKZQmgSZjtHeOOx4C5/IxlMF0ixiuT81NwTTg2Wky3KKQ8APlZYFU+Cw1VqFtObfAIVPwSBBhBzw4e59sMdmjQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mongodb-secret
      namespace: realm
