---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mongodb-secret
  namespace: realm
spec:
  encryptedData:
    mongodb.secret: AgARpfjpWmpIiP2mgydMWcwqypAYns79wVrjbB8fvbFvOLnKi2PVCbKbSybA4ULhj1tMOIpnUK3DkXNLCrXbWS/6nPFqftb3IlPDJn1v52z/smXZCKbNNVPRnAabF9A/R2ZUzcW/wJnaG7SCu8X8Crg4mNMxDWCkSmasxJDNEhfC5VfRZUlhdrDaHDzNCDKlDs98U5YL/FablNZ2d4tKKS0LhTRCvvuv266ZDpBJKI5EcVyswKi9S/zjkZTlG5JXxH79n8EZNCRhcifvV3gfDpf09Q5MxJ3rxSg0AvBQTjoKNeNghEbfuIUCHQdYM0LGgVbrhXmW5ies5jQ+ePlLpaQecbb6aLOzMNqlwc3lwtcYaWqb97eJSvnFzxpSfm0F/n4HYHUZGZFG2fgSQaUuaIUjZ7SZH6dSdGZYZs7JwCwxLdAxpmoX+R2pnOcMZLqg5cQrEYVJ7mouX8r+l3HTY3ToTvVRMBhsIcW1fSCxDnCWxmdmQ+QaXLBVVoFoBAjiy9rxHA7fs7oLFa7I8KLdzsbKrUg+bGCnKXwKYaiSMT+nEjWHlgI4lH6NDYxR8sHti4kFHj+PKKmtgcIVC6W52TqwZ6INS2paGg8gupVNL5oMfOqv0qWa2SWtrRKkk5mUAXs9tCL7cy84ISakpEl7vcp6dcO9VooHpEmuA0OlvBhC6UDOL5rQ1UQgwYSC6pkF2TtTHgO8k6WA0rWDfP+LG/Gx2ULggpotafu7bzTiUcErtdgm+b92qqyUYvlm1bBp2pnN8NS50mdiDj7o8QYsAaqFPcQ65SEGJU82HxLO98JX8jCRVl548CpyB/ddE1CO7g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mongodb-secret
      namespace: realm
