---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mongodb-secret
  namespace: realm-dev
spec:
  encryptedData:
    mongodb.secret: AgAoZclrD+UMPr8vWZP69tgb10Enf2+qjSqncy7aMiDtr9KAJraVMeLdappc7JHQGDSjM5yhzhfITyq5j8thNG0fzzEgpiRPgIlop13WLN6aTfjWLNblp2sE17hWlGRERBLCXmnt30QUMzoU3l6SMTGnB0J93GRHX8JwotWBEgkCG7lOaGXYD1H4+CFwx+E2aze1Pd/asO/3/egEyH6jaQ+fMvht4GokkPrAK6UW9EOrq5scKOgkL430skhVFB6IVSmeqJ26uOOxV6Pvci0YP4AGhILToYjTwTuwzPA8+mm8/6hbS4Dw0JhhmjOrzgYbPUjEDrbNM9IAERXgwPW/uPoD2EOooCyBDx/jpD2zvRJYS6P5/Zf9HLwvBsNEIUnE2i7G13SwXq9tjgbO2Z2uKTeDrdN1Z1u+7x+wBM0mruNGRF34qHJQgIe6xnkJ0tmU+2wRbh2Bb2eTryfx4zSlXO/bKhk4aBAf5142/vFjBOtS/mYt+LYcdxwXp4KcAsVtQorQ92gr62kHn1Ze8oIx3UoWD033rhs75iAT947ANxRz5eZR8XqehOXCEvPrbgcXN2ZdvXvMGpsTGy6T4uh+5c33yEmX9evnZuSdLR6IUjVQ5C2+9Zm2bNmdqBZiLmsECJa/gvuJZ3Nl72BfTOiJBSR6MW61iYXCq0IDDBI+rYCQp8NI4r4FJZXhdvlk7W6G4knDDopSigHCBuEHwthPrURO8JUYkoazLHiC5l6wQy6qIqoefoOj1XSBlAkJgdn+2tlRVHmp7uviB56n5DR2YWdLoqOzgxl2886hXYgiCsINyc4LTFcTwAnOHBsREQHLPQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mongodb-secret
      namespace: realm-dev
