apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "true"
  url: "https://argocd.runicrealms.com"
  additionalUrls: |
    - https://argocd.runicrealms.com
    - http://argocd.runicrealms.com
  statusbadge.url: "http://argocd.runicrealms.com/"
  accounts.admin: apiKey, login
  accounts.admin.enabled: "true"
