---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gh-pat-secret
  namespace: argocd
spec:
  encryptedData:
    gh_pat: AgCIQ5ZBeqO3MqH/KdLNC5SRcW2Y4uTC5yTasI4K6HgyUzvNSAQoxlk8k0ndBPxzLUckhuSmXz9UVS/oFLaOojJWd3RdYp4LiDjKFvGZRikruoP3Hv1ro86gcGIVLKYEUV4kvaaxcCMCnDnSQqmUp2GxAZa2tB+W7JsmRRCgjVOij7sMXwjyG+nJq53mVgVvMG5TYMfqSE3M2IuNWtN+RFVMgXsLQZCiybGz7iBcblvBgo3bknjY8ZOtdpI0usJNYK66CZ02CbAyQ+guWJ2GyPUScI6aHLa3DqIXZWYSqSqLXbC4mJqNXYLOfXv2P8zfacOz4KSjDz1GT/MXtpb6KE2tcUKN0QKUmTVpgZjIPyXNlCqi7gTBDrJ7iNHm2hIedqiCkxfqWLJqP0A0/SkjiQtliGRkBjmT1qjzJBSteP3Zi7ZcDnxsIhveY2VmyjtTvginTg8xoLvHPg8YqPwDBMStSXNcgvl7ANHG63Hrc1p7hNzJWBospOrE9Otarr8hRu30ovOl86Zy882psXsRbjHozpx6F/wPKWl+6Wz5yhssH0+ysKF4Z5elRv0ArClHDvVK0LchsrpyH86IAUPQOYKpbo1yii2NhTkZCoPEDulxtaErzutpn7bPBAB7wuwSQBRhlbkVB/yEh1BICX0MV5BMF3vn2VXTrKLxI47zrKmTckKPXOyx/8fkp8M07cDvC9IJyPRKa9GqibcaULieuaI0RwuF8uTKlN6xXu7bL+8CipwnM5pxMjy1wEljwnUUwcn8CgEzxpLOzDE26ScUrmRiBDwcnKr+U+ZXJ+KUASr5EagtJalMFFTLYhS7Tzc=
  template:
    metadata:
      name: gh-pat-secret
      namespace: argocd
