apiVersion: builtin
kind: PatchTransformer
metadata:
  name: remove-old-argocd-cm
patch: |-
  - op: replace
    path: "/metadata"
    value:
      name: argocd-cm
      namespace: argocd
target:
  kind: ConfigMap
  name: argocd-cm
