apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`registry.runicrealms.com`)
      kind: Rule
      services:
        - name: harbor-core
          port: 80
