apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`registry.runicrealms.com`)
      kind: Rule
      services:
        - name: harbor-core
          port: 80
  tls:
    certResolver: cloudflare
