apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`jenkins.runicrealms.com`)
      kind: Rule
      services:
        - name: jenkins
          port: 8080
  tls:
    certResolver: cloudflare
