---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgDxl788vuAviDh9Utaui2gCa4gF/XECmZH2645J0qh0TVPWDuhbj4dZWddJaPxfN6kSIdyoDG1u1fu3up1ZGT4GleFQAQC8KlkHGTUntWztNc9T2zIigXUFUXL6lEREr7NL0GQ/qaDQF6MCEyUlxpKM+fLH3KwPz1NiyrQuVHKyYPgSB5x8wK+3hQcA2exLZTyRo6TqQBnVxouzXMbjVkgufb1ESuP9UezWY3D1r3QvAQieOBjKPPjH6/sI7gmEWW6UDWap//jX8NNxgTUFLUxXIdLQEmXyEKaCJEmOiWRlkkVrOTJ8PU0sKSmB2t2l6stj2h36gthaRKVgux2JMkTB5WVnkbbuzpGMp8zNSrKizRbsoDtI8Cw37LcBqaQN6qZb7b7eLrp+IIPmw//2kZT6DoxVTPOXHh+a5VyVgS3nPAGMqQ6HGL54/aAEl2RIPBF2JB4Z4gKWvIKEZl06PwMdLMltsG00XtSRsB1FlfDDsj5PaaYobKfXLmNBv9YEiIS51j0RrQv+boSgFo3q3DX1c4D6F2/+mWdkbpSDwtMgFCtIkK6hcEJijaE/+LpTHwarPuBYGH5DMIhfHdR/pWb8B4PExmBLb4BKIKdWFFBzgLY/8+QnoasD9zf2HssvPyA/BxtRMJuTjE98spckUwzyLGr4ORxHfBUzvMmDVEGeJtuBnccwzNgBU3471p25JYsAawUKbfy0CdZgQ2KGvxDWgOJFSMAK9ofRlZFd1104qFMLEyILHWYINCacmJh8TDrr53K7Ud+PX7qO2aHIYfLdfJ86YYDQHllpRXJV7FpiFWCIpO+N0ZHO9KlIF7RP3XELy2Z4nUMoeXDcrNVBjWfnKAAuegqXtjnO7OAfWgHdNIi5RwVNMZ5q8Ym2Aw8HZ9/q2AU21MhF59SQTpHVbEMk9AEMomamS5lNMKxtVev1fkuLSf09EYMi/Bywk9CqyCuVvIgRZ7SitrvqzWOQV2GOtcCzaXjSkvuj4/VAWzX8C+2adIv/HQI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
