---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: jenkins
spec:
  encryptedData:
    .dockerconfigjson: AgBXLuffW1dPzhURxa3ILNa8SX8ZnQqqMO6jDQVn0h5LCg6kq0QFUdtGTZ/MWg0Vydm0Gbfe5cunSSNbDBcfg9Cp9IuZG7GNhjvxNSVf+/qPyqgICTDai6X69orRAVc9cb57tJvms49OPhftFSKpd2HzPIWrO4ile5PJmz6QauP9LlgmDZxUJv6WzK6aRp1avHS07G4eDGXXL/MIApKfXy5bkv9ScNPWubyOzWcBiQngOwW3uQdv57NGYY2KfcuElpAP/pkuG+YaWCZzIS4bTu853qUu8YTQOuK3H20MeDltdm0MeHGmIVwhXAnG0/M/wVDfPH7A/VxLXGLSEMZRqw0+IhNfUYEnsEJ8Ttt1Vk9yLGpFkyixvcWetKLclvHOG7a5wUuZxyaWHQHLtpU1v8cje6vKwEfFP9Kw2lbgVUXSTzvvxI/jkulQen6UrKkSFdh50SS/xs7GeONlK7K4N+D8XVo+t1FbnnL7idPbqDh1KgRuoF/q8dRZv5AkucQ+lGsaz7WKinyMM8JqLA7KWvUyIKHjYQJyCuBGK1SA6kLb2/NVSzZKeha4ural8bOXeXiM1ZkMGKj4jT8g7r0o3AC3D3YTs/Y/03inGZfIPh+BCZ4kVWh+5aY5zsXn6vTZAWZlUvg8H7Y5YuBwlnjB7qLGCAlMEYLrRZ255Qbq+ryk/2OWi/Ow7MjBoFvqvg6zSbiPDWkFfxLQkZeoHBoanTSTFRx/5ugBXPUD6dyvSST+m72wmshrVOeTb//CZOZjPugr9oGxOwQSyztKGSH3r0duxNh1iPGcFdQ9qVHwFjdMqlmzCTWTZ1uWTnpwDe0clPT41PzSqVts0L741kgBIIH7+LQzRwPxWvfANTE6W66SJhllGmotQ3yn0vBzqFmEFUvIeA5Mr0NRJvXZWqU8HG2LqWYytrBgPbVsbsWMlSYEU0qolaBfgwcijrj6uaWmvqbkAXONa68aoTkG09tUvPehb2EW/gTPruja7OHb+xv+B8OdAxtHagI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: jenkins
    type: kubernetes.io/dockerconfigjson
