fullnameOverride: sealed-secrets

rbac:
  create: true

serviceAccount:
  create: true
  name: sealed-secrets

controller:
  # CRDs are cluster-wide
  watchNamespace: ""  # Empty = watch all namespaces

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

networkPolicy:
  enabled: true

metrics:
  enabled: true
