apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realm-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Runic-Studios/Realm-deployment.git
    path: .
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
        - realm-dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: realm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
